on:
  push:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8'

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
        env:
          SERVICES: s3

      - name: Make test bucket
        run: awslocal --endpoint=http://localhost:4566 s3 mb s3://test-bucket

      - name : Run tests
        run: |
          bundle install
          bundle exec rspec
